"""
Dating App AI Prompts Module.
Contains optimized prompts for all AI features.
"""

from .bio_prompts import (
    BIO_SYSTEM_PROMPT,
    BIO_GENERATE_TEMPLATE,
    BIO_IMPROVE_TEMPLATE,
    BIO_FEEDBACK_TEMPLATE,
    BIO_TONES
)

from .conversation_prompts import (
    CONVERSATION_SYSTEM_PROMPT,
    CONVERSATION_STARTER_TEMPLATE,
    MESSAGE_SUGGESTION_TEMPLATE,
    ICEBREAKER_TEMPLATE,
    CONVERSATION_STYLES,
    MESSAGE_GOALS
)

from .compatibility_prompts import (
    COMPATIBILITY_SYSTEM_PROMPT,
    COMPATIBILITY_ANALYSIS_TEMPLATE,
    QUICK_COMPATIBILITY_TEMPLATE,
    COMPATIBILITY_INSIGHTS_TEMPLATE
)

from .icebreaker_prompts import (
    ICEBREAKER_SYSTEM_PROMPT,
    ICEBREAKER_GENERATE_TEMPLATE,
    ICEBREAKER_CATEGORIES,
    ICEBREAKER_TEMPLATES_BY_INTEREST,
    ICEBREAKER_DIFFICULTY
)

from .review_prompts import (
    REVIEW_SYSTEM_PROMPT,
    PROFILE_REVIEW_TEMPLATE,
    QUICK_REVIEW_TEMPLATE,
    PHOTO_ADVICE_TEMPLATE,
    PROMPT_SUGGESTIONS_TEMPLATE,
    PROFILE_ASPECTS
)

__all__ = [
    # Bio
    "BIO_SYSTEM_PROMPT",
    "BIO_GENERATE_TEMPLATE",
    "BIO_IMPROVE_TEMPLATE",
    "BIO_FEEDBACK_TEMPLATE",
    "BIO_TONES",
    # Conversation
    "CONVERSATION_SYSTEM_PROMPT",
    "CONVERSATION_STARTER_TEMPLATE",
    "MESSAGE_SUGGESTION_TEMPLATE",
    "ICEBREAKER_TEMPLATE",
    "CONVERSATION_STYLES",
    "MESSAGE_GOALS",
    # Compatibility
    "COMPATIBILITY_SYSTEM_PROMPT",
    "COMPATIBILITY_ANALYSIS_TEMPLATE",
    "QUICK_COMPATIBILITY_TEMPLATE",
    "COMPATIBILITY_INSIGHTS_TEMPLATE",
    # Icebreaker
    "ICEBREAKER_SYSTEM_PROMPT",
    "ICEBREAKER_GENERATE_TEMPLATE",
    "ICEBREAKER_CATEGORIES",
    "ICEBREAKER_TEMPLATES_BY_INTEREST",
    "ICEBREAKER_DIFFICULTY",
    # Review
    "REVIEW_SYSTEM_PROMPT",
    "PROFILE_REVIEW_TEMPLATE",
    "QUICK_REVIEW_TEMPLATE",
    "PHOTO_ADVICE_TEMPLATE",
    "PROMPT_SUGGESTIONS_TEMPLATE",
    "PROFILE_ASPECTS",
]
