import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal & Disclaimer - FOR THE KIDS',
  description: 'Legal notice and disclaimer for FOR THE KIDS Transparency Dashboard.',
};

export default function LegalPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-8 md:p-12">
        <h1 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-8">
          LEGAL NOTICE & DISCLAIMER
        </h1>

        <div className="space-y-8">
          {/* Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
              Limitation of Liability
            </h2>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              The information and product details generated by our AI are for demonstration and
              informational purposes only. It does not constitute legal, financial, or professional
              advice. We assume no liability for the accuracy, completeness, or consequences of
              using the AI-generated content.
            </p>
          </section>

          {/* User Responsibilities */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
              User Responsibilities
            </h2>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              Users are solely responsible for reviewing, verifying, and editing all generated
              content before publishing it on any marketplace.
            </p>
          </section>

          {/* Illustrative Purposes */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
              Illustrative Purposes
            </h2>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              All marketplace statistics shown are for illustrative purposes only.
            </p>
          </section>
        </div>

        {/* Copyright */}
        <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-700">
          <p className="text-slate-500 dark:text-slate-400 text-sm">
            &copy; 2026 AI Solutions Store. Operated for charitable purposes.
          </p>
        </div>
      </div>
    </div>
  );
}
